apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: 887395516997.dkr.ecr.us-east-1.amazonaws.com/cloudshootout:latest
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: rds-db-credentials
                key: host
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: rds-db-credentials
                key: username
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: rds-db-credentials
                key: password
